language: php
php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
before_script:
  - export QINIU_ACCESS_KEY="QWYn5TFQsLLU1pL5MFEmX3s5DmHdUThav9WyOWOm"
  - export QINIU_SECRET_KEY="Bxckh6FA-Fbs9Yt3i3cbKVK22UPBmAOHJcL95pGz"
  - export QINIU_BUCKET_NAME="phpsdk"
  - export QINIU_KEY_NAME="file_name"
  - export QINIU_TEST_ENV="travis"
  - composer install --prefer-source
script:
  - ./vendor/bin/phpcs --standard=PSR2 src
  - ./vendor/bin/phpcs --standard=PSR2 tests
  - ./vendor/bin/phpunit
